apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: AppGroup
metadata:
  name: online-boutique
spec:
  numMembers: 11
  topologySortingAlgorithm: AlternateKahn
  workloads:
    - workloadName: frontend
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: frontend
      dependencies:
        - workloadName: cartservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: productcatalogservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: currencyservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: shippingservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: adservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workloadName: cartservice
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: cartservice
      dependencies:
        - workloadName: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: redis-cart
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workloadName: productcatalogservice
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: productcatalogservice
      dependencies:
        - workloadName: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: recommendationservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workloadName: currencyservice
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: currencyservice
      dependencies:
        - workloadName: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workloadName: paymentservice
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: paymentservice
      dependencies:
        - workloadName: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workloadName: shippingservice
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: shippingservice
      dependencies:
        - workloadName: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workloadName: emailservice
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: emailservice
      dependencies:
        - workloadName: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workloadName: checkoutservice
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: checkoutservice
      dependencies:
        - workloadName: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: cartservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: productcatalogservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: currencyservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: paymentservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: shippingservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: emailservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workloadName: recommendationservice
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: recommendationservice
      dependencies:
        - workloadName: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workloadName: productcatalogservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workloadName: adservice
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: adservice
      dependencies:
        - workloadName: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workloadName: redis-cart
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: redis-cart
      dependencies:
        - workloadName: cartservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
