apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: AppGroup
metadata:
  name: online-boutique
spec:
  numMembers: 11
  topologySortingAlgorithm: AlternateKahn
  workloads:
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: frontend
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: cartservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: productcatalogservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: currencyservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: shippingservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: adservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: cartservice
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload: redis-cart
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: redis-cart
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: productcatalogservice
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: recommendationservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: currencyservice
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: paymentservice
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: shippingservice
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: emailservice
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: checkoutservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: checkoutservice
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: cartservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: productcatalogservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: currencyservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: paymentservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: shippingservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: emailservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: recommendationservice
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: productcatalogservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: adservice
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: frontend
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: redis-cart
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: cartservice
          minBandwidth: "100Mi"
          maxNetworkCost: 80
