apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: AppGroup
metadata:
  name: redis-cluster
spec:
  numMembers: 2
  topologySortingAlgorithm: AlternateKahn
  workloads:
    - workloadName: redis-leader
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: redis-leader
      dependencies:
        - workloadName: redis-follower
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workloadName: redis-follower
      workloadRef:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: redis-follower
