apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: AppGroup
metadata:
  name: redis-cluster
spec:
  numMembers: 2
  topologySortingAlgorithm: AlternateKahn
  pods:
    - podName: redis-leader
      dependencies:
        - podName: redis-follower
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - podName: redis-follower
