apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: AppGroup
metadata:
  name: redis-cluster
spec:
  numMembers: 2
  topologySortingAlgorithm: AlternateKahn
  workloads:
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: redis-leader
      dependencies:
        - workload:
            kind: Deployment
            apiVersion: apps/v1
            namespace: default
            name: redis-follower
          minBandwidth: "100Mi"
          maxNetworkCost: 80
    - workload:
        kind: Deployment
        apiVersion: apps/v1
        namespace: default
        name: redis-follower
